//Attached to TilePrefab. Gives a "in-scene" reference to the Nodes generated by the Grid. Changes materials based on the state of the Node it's attached to. 

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Tile : MonoBehaviour {

    public Node carryingNode;
    public Material[] tileMatArray;
    public MeshRenderer meshRend;

    public Material baseMaterial;


    public void ReconfigureMats()
    {
        if (carryingNode.IsAttackable)
        {
            SetAuxTileMaterial(5);
            return;
        }

        if (carryingNode.IsOnPath)
        {
            SetAuxTileMaterial(4);
            return;
        }

        if (carryingNode.IsOccupied)
        {
            SetAuxTileMaterial(3);
            return;
        }

        if (carryingNode.IsSelectable)
        {
            SetAuxTileMaterial(2);
            return;
        }

        ResetTileMatToBase();
    }


    public void SetAuxTileMaterial(int materialIndex)
    {
        meshRend.sharedMaterial = tileMatArray[materialIndex];
        //Debug.Log(gameObject.name + ": Color Changed to - " + tileArray[materialIndex].name);
    }

    public void SetBaseTileMaterial (int materialIndex)
    {
        baseMaterial = tileMatArray[materialIndex];
    }

    public void ResetTileMatToBase()
    {
        if(baseMaterial != null)
        {
            meshRend.sharedMaterial = baseMaterial;
        }
        else
        {
            tileMatArray[0] = baseMaterial;
            meshRend.sharedMaterial = baseMaterial;
        }
    }
}
